### ISSUE TITLE
Feature request: check if sensor is present

### ISSUE THREAD

**Issue by FerGT50** [malokhvii-eduard/arduino-bme280#5] opened 2023-12-19 14:33 UTC
Hello,
using BME280 in I2C with ESP32. Arduino IDE 1.8.19, latest Arduino-ESP32 core (2.0.14).

Even if no sensor is attached I can call sensor.begin(), setSettings(), getTemperature() etc.: I can't seem to have a way to tell if a sensor is actually present/working.

It would be nice to have for, example, begin() returning false if the BME280 is not attached or not responding.
Or maybe it already works this way, but I cannot find the API documentation so I don't know if begin() returns something.

Thanks for reading.

**Comment by malokhvii-eduard** [comment] 2023-12-19 18:26
@FerGT50 Duplicate of #2.

**Comment by malokhvii-eduard** [comment] 2023-12-19 22:06
@FerGT50 Thank you for suggestion, I will update the FAQ section in the README.

**Closed as completed** 2024-03-13 10:08 UTC
Labels: duplicate
